### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by niklaswimmer** [declantsien/cargo-ninja#2]
Hey there, I just noticed that this project has no license yet. In the Rust community it is fairly common to use a MIT/Apache2 dual license, you are of course free to choose a different one however (or stay with none). In any case, it would be beneficial to make it explicit.

I would really like to use this project, but without a license I can not be sure if I am allowed to[^1] :)

[^1]: https://choosealicense.com/no-permission/

**Comment by niklaswimmer** [comment]
Whee, I just noticed that the `Cargo.toml` actually does specify a license. Having a license file would still not hurt tho, to have it displayed by GitHub, so I will leave this open.

**Comment by declantsien** [comment]
Sure. Will add a license file later today.

**Comment by declantsien** [comment]
https://github.com/declantsien/cargo-ninja/commit/4d01be78e3baa1bb144ffe7fd234f5db2806f0d9
